[package]
name="sandbox"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
publish.workspace = true

[dependencies]
jsonwebtoken.workspace = true
serde.workspace = true
time.workspace = true