[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[config]
default_to_workspace = false

[tasks.db-prepare]
command = "cargo"
args = ["sqlx","prepare", "--workspace"]

[tasks.fmt] 
command = "cargo"
args = ["fmt"]

[tasks.clippy]
command = "cargo"
args = ["clippy","--fix","--allow-dirty"]

[tasks.typos]
command = "typos"
args = ["-w"]

[tasks.update]
command = "cargo"
args = ["update"]

[tasks.build]
command = "cargo"
args = ["build"]
dependencies = ["fmt","clippy","typos","update"]

[tasks.test]
command = "cargo"
args = ["test"]
dependencies = ["build"]


[tasks.ci]
description = "事前に対応するDBのDockerコンテナを起動しておくこと"
# todo: コンテナ起動タスクを追加する
dependencies = ["test"]
