[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true
DB_CONTAINER_NAME = "shuttle_ubiquitimes-cardiac_shared_postgres"

[config]
default_to_workspace = false

[tasks.db-prepare]
command = "cargo"
args = ["sqlx","prepare", "--workspace"]

[tasks.container-start]
command = "docker"
args = ["container","start","${DB_CONTAINER_NAME}"]

[tasks.container-stop]
command = "docker"
args = ["container","stop","${DB_CONTAINER_NAME}"]

[tasks.fmt] 
command = "cargo"
args = ["fmt"]
dependencies = ["container-start"]

[tasks.clippy]
command = "cargo"
args = ["clippy","--fix","--allow-dirty"]

[tasks.typos]
command = "typos"
args = ["-w"]

[tasks.update]
command = "cargo"
args = ["update"]

[tasks.build]
command = "cargo"
args = ["build"]
dependencies = ["fmt","clippy","typos","update"]

[tasks.test]
command = "cargo"
args = ["test"]
dependencies = ["build"]


[tasks.ci]
description = "事前に対応するDBのDockerコンテナを起動しておくこと"
dependencies = ["test"]
run_task = "container-stop"
