[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[tasks.fmt]
command = "cargo"
args = ["watch","-x", "fmt"]


[tasks.ci]
dependencies = ["fmt-ci","test-ci", "clippy-ci", "machete-ci", "typos-ci"]

[tasks.fmt-ci]
command = "cargo"
args = ["fmt"]

[tasks.test-ci]
command = "cargo"
args = ["test"]

[tasks.clippy-ci]
command = "cargo"
args = ["clippy", "--fix"]

[tasks.machete-ci]
command = "cargo"
args = ["machete", "--fix"]

[tasks.typos-ci]
command = "typos"
args = ["-w"]

[tasks.build-ci]
command = "cargo"
args = ["build"]



