[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[tasks.fmt]
command = "cargo"
args = ["watch","-x", "fmt"]


[tasks.ci]
script = [
'''
cargo fmt
cargo test
cargo clippy --fix --allow-dirty
typos -w
cargo update
cargo check
'''
]
