[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[tasks.fmt] 
command = "cargo"
args = ["fmt"]

[tasks.clippy]
command = "cargo"
args = ["clippy","--fix","--allow-dirty"]

[tasks.typos]
command = "typos"
args = ["-w"]

[tasks.update]
command = "cargo"
args = ["update"]

[tasks.build]
command = "cargo"
args = ["build"]
dependencies = ["fmt","clippy","typos","update"]

[tasks.test]
command = "cargo"
args = ["test"]
dependencies = ["build"]


[tasks.my_ci]
dependencies = ["test"]

[tasks.my_flow]
command = "echo"
args = ["my_flow"]
dependencies = ["test"]