[package]
name = "share"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
publish.workspace = true

[dependencies]
rand.workspace = true
sqlx.workspace = true
testcontainers.workspace = true
testcontainers-modules.workspace = true
